### ISSUE TITLE
Support multi-order Healpix value maps

### ISSUE THREAD

**Issue by hombit** [cds-astro/cds-healpix-rust#11]
It would be great if the package could support a generalized version of MOC, which would support any arbitrary value types. It would also be interesting to have some tooling to support different strategies for tile merging and splitting.

I have some implementation of this idea in [this repo](https://github.com/hombit/mom-builder), and would be happy to port that code to this project. If it sounds good to you, I'll open a draft PR, and ask you to review it and open some fine-grained issues.

**Comment by fxpineau** [comment]
I made a first version of the MOM abstraction in the `cdshealpix::nested::map::mom`,
together with a very basic implementation as a single vector of ordered `(zuniq, value)` tuples.
I would like to have a `skymap` abstraction to `mom` implementation
(with abstractions for deciding how to merge values, ...: yet TBD and that could come from your code).

Do you think you could implement this abstraction on your MOM implementation?
And/or support the skymap abstraction as an input of your code?
(I have not checked how compatible both your and the cdshealpix codes are compatible)

**Comment by hombit** [comment]
@fxpineau thank you, I'll do it! Let's move this discussion to the PR?
