### ISSUE TITLE
Build issues with python3.10

### ISSUE THREAD

**Issue by bsipocz** [cds-astro/cds-healpix-rust#2]
I run into these build issue when trying to use the package (as a non-direct dependency of astroquery) in CI using Python3.10. I haven't investigated the errors in detail myself, please let me know if you think it's an issue we can/should fix downstream.

Build traceback starts around here:
https://github.com/astropy/astroquery/runs/4074169564?check_suite_focus=true#step:5:393

**Comment by fxpineau** [comment]
@bsipocz (sorry I was off last week), I am working on it, updating dependencies.
Note that the error does not come from this project but from the [cds-healpix-python](https://github.com/cds-astro/cds-healpix-python) wrapper.
